### PR TITLE
Backport winapi 0.3 to v0.1.x branch

### LINKED ISSUE #16: Release winapi bump
the latest released version of iovec currently depends on winapi 0.2, while the master is already bumped to 0.3. Any chance we can get a release including this change? :)

### PR DESCRIPTION
**Pull request by pravic**
fixes #16.

I understand your concerns about iovec 0.2, but nothing prevents you from releasing this patch update for iovec 0.1.

### CODE REVIEW

**Comment by carllerche** [comment]
It looks like we cannot back port winapi 0.3 because it has dropped support for older Rust versions.

**Comment by nox** [comment]
Can we just release a new breaking version of everything with winapi 0.3 and be done with it, *please*?

**Comment by carllerche** [comment]
@nox If I released `iovec` 0.2 without updating mio, tokio, etc... would that help you?

**Comment by cramertj** [comment]
I also need this patch, but would not find it useful at all if it was released as an 0.2 (without bumps to the corresponding libraries). @carllerche Is there a particular version of rustc that you're targeting support for that this would drop? Is there a timeline after which this change would be accepted?

**Comment by carllerche** [comment]
It should track Mio, which is on 1.18: https://github.com/carllerche/mio/blob/master/.travis.yml#L27

I don't know what winapi 0.3 supports.

**Comment by nox** [comment]
https://github.com/retep998/winapi-rs/blob/0.3/appveyor.yml#L7

1.6.0 it seems. @carllerche where did you get that info about winapi 0.3 dropping old Rust support?

I just don't understand why you are so reluctant to make breaking changes to crates that are in development and didn't reach 1.0.

**Comment by cramertj** [comment]
@nox 
> I just don't understand why you are so reluctant to make breaking changes to crates that are in development and didn't reach 1.0.

FWIW large parts of the futures and tokio ecosystem depend on this crate, since it's the basis for vectorized IO.

**Comment by retep998** [comment]
>This crate [winapi] depends on Rust 1.6 or newer on Windows. On other platforms this crate is a no-op and should compile with Rust 1.2 or newer.

>It should track Mio, which is on 1.18

>It looks like we cannot back port winapi 0.3 because it has dropped support for older Rust versions.

**Comment by carllerche** [comment]
Yes, I just glanced at the CI super fast, saw a rust version error and assumed it was due to this PR. It is, in fact, unrelated.

**Comment by Keruspe** [comment]
Any news regarding this?

**Comment by Keruspe** [comment]
From what I understand, libc doesn't support rust 1.9 anymore, which leads to the fialure on travis.
@carllerche as you're saying the actual target is the one from mio (e.g. 1.18), maybe you can update the travis config to test on 1.18 and not 1.9, so that this PR passes CI and we can get a release?

**Comment by chandde** [comment]
any update on this?

**Comment by carllerche** [comment]
This has not been merged due to Mio being stuck on its winapi version until a breaking change happens. 

That said, iovec is landing in std stable very soon. Given that, this crate is in track to be deprecated.

**Pull request closed without merging**
