### PR TITLE
Release 0.1.2

### LINKED ISSUE #12: Release 0.1.2 ?
Hi there,

Would you mind to release a patch version with only the wasm support (or to move db866454eb31b3dafe0308fff3e8551744f6c654 out of `master` branch)?

It seems that some people are stuck because of this https://github.com/DenisKolodin/yew/pull/110

Thanks

### PR DESCRIPTION
**Pull request by ctjhoa**
Fix #12

### CODE REVIEW

**Comment by carllerche** [comment]
I think the "backport" is actually going to require some reimplementation as the strategy used in 0.1 is significantly different than 0.2.

**Comment by Victor-Savu** [comment]
Well, at least the current master does build on the wasm32-unknown-unknown target, as opposed to v0.1.2, so even that would be worth a release.

**Comment by carllerche** [comment]
Unfortunately, the current master represents an 0.2 release. While technically it is possible to release now, there are a few issues.

1) None of the downstream dependencies (mio, bytes, ...) are going to update to it imminently.
2) The new API has not been validated by these downstream dependencies yet.

The best strategy for getting wasm support working will be to back port the fix.

**Comment by ctjhoa** [comment]
@carllerche this should be better.

**Comment by carllerche** [comment]
Ok! Waiting for CI to pass.

**Comment by carllerche** [comment]
published.

**Pull request merged**
