### PR TITLE
Add support for non-windows/unix targets

### PR DESCRIPTION
**Pull request by dflemstr**
This is mostly for wasm support and I'm not sure if this approach is great for other targets.

I could also add a continuous integration job for this target if necessary.

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks.

Could you provide more context about how this would be used on `wasm`? Also, a CI branch would be appreciated.

I also think this is based on the 0.1.x branch. I switched master to represent 0.2.x. This can be handled in a separate PR though.

**Comment by dflemstr** [comment]
@carllerche There is no `iovec` concept in wasm AFAIK since that is a UNIX (POSIX?) specific concept.  Since the heap isn't segmented I don't see an advantage in tracking iovec memory at all on that architecture, since I can't think of anything reasonable a `readv(2)` implementation could use it for.

This PR is of course a bit generic since it assumes no `iovec` support by default on unknown platforms.  Maybe it's better to cause a compilation error and whitelist specific architectures?

**Comment by dflemstr** [comment]
Not sure why the build is failing; it builds locally...

**Comment by carllerche** [comment]
Is there a way to run wasm targets in CI?

I guess at the very least, CI compiles but doesn't run?

**Comment by dflemstr** [comment]
@carllerche it's possible to run them using a significant amount of node.js scaffolding.  What would you like to do? Create a program that exercises this code path?

**Comment by koute** [comment]
> Is there a way to run wasm targets in CI?

At least on Travis you can run all of the Rust's web targets pretty easily with [`cargo-web`](https://github.com/koute/cargo-web) **if** that's what you want; for example:

```
# Install nodejs
nvm install 9

# Unfortunately we don't have binary packages for cargo-web yet
cargo install cargo-web

rustup target add asmjs-unknown-emscripten
cargo web test --nodejs --target-asmjs-emscripten

rustup target add wasm32-unknown-emscripten
cargo web test --nodejs --target-webasm-emscripten

set +e
echo "$(rustc --version)" | grep -q "nightly"
if [ "$?" = "0" ]; then
    export IS_NIGHTLY=1
else
    export IS_NIGHTLY=0
fi
set -e

if [ "$IS_NIGHTLY" = "1" ]; then
    rustup target add wasm32-unknown-unknown
    cargo web test --nodejs --target-webasm
fi
```

That will run the tests for all three web targets using nodejs. Running the tests in a headless chromium is also supported for the `*-emscripten` targets (if you don't pass the `--nodejs` flag), but you wouldn't really need that.

Just please note that right now a lot of stuff on the `wasm32-unknown-unknown` target (like, for example, `println!` calls) do nothing, so if the tests on that target fail you won't know what went wrong. Once https://github.com/rust-lang/rust/pull/47102 lands I'll add support for it in `cargo-web` so that `println!` and such will work.

**Comment by carllerche** [comment]
Interesting. I'm less interested in getting full test parity, mostly ensure things "work" at some level.

**Comment by carllerche** [comment]
Ok, I think this is good now. Thanks!

**Pull request merged**
