### PR TITLE
Backport winapi 0.3 to v0.1.x branch

### LINKED ISSUE #16: Release winapi bump
the latest released version of iovec currently depends on winapi 0.2, while the master is already bumped to 0.3. Any chance we can get a release including this change? :)

### PR DESCRIPTION
**Pull request by Keruspe**
Fixes #16 

Replaces #19

### CODE REVIEW

**Comment by philipktlin** [comment]
Any reason why this PR is not merged back to master?  I have been waiting for it for a long time.

**Comment by carllerche** [comment]
What is the urgency for this PR? Mio has a dependency on `winapi` 0.2. By merging this PR, depending on mio will then pull in two versions of winapi.

**Comment by philipktlin** [comment]
Since our project need to support in ARM therefore upgrading iovec to use winapi 0.3.5 will unblock us.  Why mio need to pull in 2 versions of winapi? if you are going to upgrade iovec reference in mio to 0.3, then you can also get rid of winapi 0.2.6 reference in mio, right?

**Comment by carllerche** [comment]
Mio has an explicit dependency on winapi 0.2 as part of the public API. Unfortunately, we cannot get rid of winapi 0.2 w/o a breaking change.

Including winapi as part of the mio public API was a mistake. Mio 0.7 will fix this, but because Mio is also a public dependency of a number of large downstream crates, issuing breaking releases is very hard.

**Comment by carllerche** [comment]
There will probably not be a breaking release of mio until after `Future` lands in stable rust.

**Comment by Keruspe** [comment]
@carllerche There's no urgency, but these kind of bumps have to go from the ground up.
Having this in iovec would allow projects using iovec but not mio not to carry a winapi 0.2 dependency, and it will be required eventually anyways, so why not now?
Having mio depend on two versions of winapi until its public API changes doesn't seem too terrible given that most projects using mio already depend on both...

**Comment by carllerche** [comment]
I'm guessing you mean `bytes`? If so, I can look into moving the `iovec` support behind a feature flag.

**Comment by repi** [comment]
We ran into this as well and really would want to get rid of the very slow compiling `winapi 0.2`, and `iovec` is the primary dependency we have that pulls it in.

A feature flag on `bytes` for `iovec` would be nice, but don't think it would be practical as so many crates include `bytes` and would be painful to get all of them to update and use `default-features = false`. Best would be to update `iovec 0.1` here.

**Comment by carllerche** [comment]
@repi again, the problem here is `mio` depends on `winapi` 0.2 and has no ability to remove this dependency until 0.7 (which is actively in the works).

If `iovec` updates its dependency, then mio and tokio will pull in both winapi 0.2 and winapi 0.3.

I agree the situation is less than ideal. The path forward is to switch to `std::IoSlice` and move away from this crate.

Until then, I would be happy to work on a fix in 0.1 that does not force mio to depend on both winapi 0.2 and 0.3.

**Comment by repi** [comment]
Right. Took a look at this crate and didn't realize how small the dependency was on `winapi`, already have a fix that doesn't use `winapi`. Will do a separate PR.

**Comment by atouchet** [comment]
The winapi dependency was removed in #25. This can probably be closed.

**Pull request closed without merging**
