### PR TITLE
libc: require 0.2.3

### PR DESCRIPTION
**Pull request by mathstuf**
This version introduced the iovec calls.

### CODE REVIEW

**Comment by mathstuf** [comment]
Ping @carllerche

**Comment by carllerche** [comment]
thanks :+1:

**Comment by mathstuf** [comment]
A release with this would allow me to follow up through the other PRs blocking this. Just a reminder, no rush; holidays and all mean I likely won't get back to it until next week either :) .

**Comment by djc** [comment]
@carllerche ping, might be nice to get this released?

**Comment by mathstuf** [comment]
Friendly reminder that there's still been no release :) .

**Pull request merged**
